- name: Forks and Serial Demo
  hosts: all
  order: sorted
  gather_facts: false
  # serial: 7
  max_fail_percentage: 35
  serial:
    - 10%
    - 30%
    - 50%
    - 100%
  vars:
    someservers:
      - 172.25.250.11
      - serverc.lab.example.com
  tasks:
  - name: is database OK
    command: sleep 2
    run_once: true
    
  - name: Take down device from LB
    command: sleep 2

  - name: Update OS
    command: sleep 2
    failed_when: inventory_hostname in someservers

  - name: Update other Config
    command: sleep 2

  - name: Put device back to LB
    command: sleep 2
