- name: Roles Demo
  hosts: dev
  gather_facts: false
  serial: 1
  order: sorted


  tasks:
    - name: Extra Task
      ansible.builtin.shell: sleep 2

    - name: Check if Web Server UP
      ansible.builtin.uri:
        url: http://servera.lab.example.com
        return_content: true
